### PR TITLE
Bug 1257520 - add tests that call auth.testAuthenticate endpoint

### PR DESCRIPTION
**Pull request by petemoore**
This wasn't at all important, but at the same time it was trivial to implement, so I did this so we can at least close the bug.

These tests are plain java conversions of the equivalent go tests ([this](https://github.com/taskcluster/taskcluster-client-go/blob/8c0f081d4a444cf2169684a1b1eb0ead6183fc45/creds_test.go#L50-L120) plus [this](https://github.com/taskcluster/taskcluster-client-go/blob/8c0f081d4a444cf2169684a1b1eb0ead6183fc45/creds_test.go#L157-L209)).

At the same time I took the liberty of adding an auto source formatter, since that makes life much more pleasant.

### CODE REVIEW

**Comment by petemoore** [comment]
Funny, tests pass locally - I'll look into why they are failing in travis in the morning...

**Comment by petemoore** [comment]
So this is a failure in travis:

```
Dec 19, 2017 7:42:07 PM com.google.api.client.http.HttpRequest execute
CONFIG: -------------- REQUEST  --------------
POST https://auth.taskcluster.net/v1/test-authenticate
Accept-Encoding: gzip
Authorization: Hawk id="tester", ts="1513712527", nonce="5LrnWD", ext="eyJjZXJ0aWZpY2F0ZSI6eyJ2ZXJzaW9uIjoxLCJzY29wZXMiOlsic2NvcGU6MSIsInNjb3BlOjIiXSwic3RhcnQiOjE1MTM3MTI1Mjc3MTcsImV4cGlyeSI6MTUxMzcxNjEyNzcxNywic2VlZCI6Ino1b2VSLW1VVFNpcVJrSkxxU1daRHd1VzdGb1FkWVJqT0JvU1JxSjZ6MVdnIiwic2lnbmF0dXJlIjoiMzlzWHVxejJNenkzV05MREM3MWQ3SkVKMldXQlFibWlwandwWXdTWnBmUVx1MDAzZCJ9fQ==", mac="QY5PTo7ZnF0U+gbmikIRdKyOvRXnI9XC9Ut5i4Xqrwo="
User-Agent: Google-HTTP-Java-Client/1.20.0 (gzip)
Content-Type: application/json
Content-Length: 57
Dec 19, 2017 7:42:07 PM com.google.api.client.http.HttpRequest execute
CONFIG: curl -v --compressed -X POST -H 'Accept-Encoding: gzip' -H 'Authorization: Hawk id="tester", ts="1513712527", nonce="5LrnWD", ext="eyJjZXJ0aWZpY2F0ZSI6eyJ2ZXJzaW9uIjoxLCJzY29wZXMiOlsic2NvcGU6MSIsInNjb3BlOjIiXSwic3RhcnQiOjE1MTM3MTI1Mjc3MTcsImV4cGlyeSI6MTUxMzcxNjEyNzcxNywic2VlZCI6Ino1b2VSLW1VVFNpcVJrSkxxU1daRHd1VzdGb1FkWVJqT0JvU1JxSjZ6MVdnIiwic2lnbmF0dXJlIjoiMzlzWHVxejJNenkzV05MREM3MWQ3SkVKMldXQlFibWlwandwWXdTWnBmUVx1MDAzZCJ9fQ==", mac="QY5PTo7ZnF0U+gbmikIRdKyOvRXnI9XC9Ut5i4Xqrwo="' -H 'User-Agent: Google-HTTP-Java-Client/1.20.0 (gzip)' -H 'Content-Type: application/json' -d '@-' -- 'https://auth.taskcluster.net/v1/test-authenticate' << $$$
Dec 19, 2017 7:42:07 PM com.google.api.client.util.LoggingByteArrayOutputStream close
CONFIG: Total: 57 bytes
Dec 19, 2017 7:42:07 PM com.google.api.client.util.LoggingByteArrayOutputStream close
CONFIG: {"clientScopes":["scope:*"],"requiredScopes":["scope:1"]}
Dec 19, 2017 7:42:07 PM com.google.api.client.http.HttpResponse <init>
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 401 Unauthorized
Server: Cowboy
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS,GET,HEAD,POST,PUT,DELETE,TRACE,CONNECT
X-Content-Type-Options: nosniff
Connection: keep-alive
Date: Tue, 19 Dec 2017 19:42:05 GMT
Access-Control-Allow-Headers: X-Requested-With,Content-Type,Authorization,Accept,Origin
Via: 1.1 vegur
Strict-Transport-Security: max-age=7776000000; includeSubDomains
Etag: W/"1bf-OL220vU3E7IkKFfGYQQr5dZM0x0"
Cache-Control: no-store no-cache must-revalidate
Access-Control-Request-Method: *
Content-Security-Policy: report-uri /__cspreport__;default-src 'none';frame-ancestors 'none';
Www-Authenticate: hawk
Content-Length: 447
Content-Type: application/json; charset=utf-8
null
org.mozilla.taskcluster.client.APICallFailure: com.google.api.client.http.HttpResponseException: 401 Unauthorized
	at org.mozilla.taskcluster.client.TaskclusterRequestHandler.apiCall(TaskclusterRequestHandler.java:140)
	at org.mozilla.taskcluster.client.auth.Auth.testAuthenticate(Auth.java:521)
	at org.mozilla.taskcluster.client.APITest.tempCred(APITest.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
Caused by: com.google.api.client.http.HttpResponseException: 401 Unauthorized
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1061)
	at org.mozilla.taskcluster.client.TaskclusterRequestHandler.apiCall(TaskclusterRequestHandler.java:126)
	... 27 more
```

and this is the same test passing locally:

```
Dec 20, 2017 9:34:23 AM com.google.api.client.http.HttpRequest execute
KONFIGURATION: -------------- REQUEST  --------------
POST https://auth.taskcluster.net/v1/test-authenticate
Accept-Encoding: gzip
Authorization: Hawk id="tester", ts="1513758863", nonce="7FcW26", ext="eyJjZXJ0aWZpY2F0ZSI6eyJ2ZXJzaW9uIjoxLCJzY29wZXMiOlsic2NvcGU6MSIsInNjb3BlOjIiXSwic3RhcnQiOjE1MTM3NTg4NjMzNDgsImV4cGlyeSI6MTUxMzc2MjQ2MzM0OCwic2VlZCI6IjNWeWdjVF9ZU2oyOWc2M1Y5c3NYT0F1aGNqVDJLSFFhZU5iQzJHRVQwdm5nIiwic2lnbmF0dXJlIjoiYWdKSTNIY1FvclpIaWxRbjAvWko0RE4vSmFpMmRublA5NTJVZUIyYUd2Z1x1MDAzZCJ9fQ==", mac="21XIOAen/aSECqkUmJgRLik6+A20No/PVZQas5un5hE="
User-Agent: Google-HTTP-Java-Client/1.20.0 (gzip)
Content-Type: application/json
Content-Length: 57

Dec 20, 2017 9:34:23 AM com.google.api.client.http.HttpRequest execute
KONFIGURATION: curl -v --compressed -X POST -H 'Accept-Encoding: gzip' -H 'Authorization: Hawk id="tester", ts="1513758863", nonce="7FcW26", ext="eyJjZXJ0aWZpY2F0ZSI6eyJ2ZXJzaW9uIjoxLCJzY29wZXMiOlsic2NvcGU6MSIsInNjb3BlOjIiXSwic3RhcnQiOjE1MTM3NTg4NjMzNDgsImV4cGlyeSI6MTUxMzc2MjQ2MzM0OCwic2VlZCI6IjNWeWdjVF9ZU2oyOWc2M1Y5c3NYT0F1aGNqVDJLSFFhZU5iQzJHRVQwdm5nIiwic2lnbmF0dXJlIjoiYWdKSTNIY1FvclpIaWxRbjAvWko0RE4vSmFpMmRublA5NTJVZUIyYUd2Z1x1MDAzZCJ9fQ==", mac="21XIOAen/aSECqkUmJgRLik6+A20No/PVZQas5un5hE="' -H 'User-Agent: Google-HTTP-Java-Client/1.20.0 (gzip)' -H 'Content-Type: application/json' -d '@-' -- 'https://auth.taskcluster.net/v1/test-authenticate' << $$$
Dec 20, 2017 9:34:23 AM com.google.api.client.util.LoggingByteArrayOutputStream close
KONFIGURATION: Total: 57 bytes
Dec 20, 2017 9:34:23 AM com.google.api.client.util.LoggingByteArrayOutputStream close
KONFIGURATION: {"clientScopes":["scope:*"],"requiredScopes":["scope:1"]}
Dec 20, 2017 9:34:23 AM com.google.api.client.http.HttpResponse <init>
KONFIGURATION: -------------- RESPONSE --------------
HTTP/1.1 200 OK
Server: Cowboy
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS,GET,HEAD,POST,PUT,DELETE,TRACE,CONNECT
X-Content-Type-Options: nosniff
Connection: keep-alive
Date: Wed, 20 Dec 2017 08:34:23 GMT
Access-Control-Allow-Headers: X-Requested-With,Content-Type,Authorization,Accept,Origin
Via: 1.1 vegur
Strict-Transport-Security: max-age=7776000000; includeSubDomains
Etag: W/"4a-wV1iFXopUxbTnJAKQzWV5KlBej8"
Cache-Control: no-store no-cache must-revalidate
Access-Control-Request-Method: *
Content-Security-Policy: report-uri /__cspreport__;default-src 'none';frame-ancestors 'none';
Content-Length: 74
Content-Type: application/json; charset=utf-8

Dec 20, 2017 9:34:23 AM com.google.api.client.util.LoggingByteArrayOutputStream close
KONFIGURATION: Total: 74 bytes
Dec 20, 2017 9:34:23 AM com.google.api.client.util.LoggingByteArrayOutputStream close
KONFIGURATION: {
  "clientId": "tester",
  "scopes": [
    "scope:1",
    "scope:2"
  ]
}
```

**Comment by petemoore** [comment]
There are three differences in the http response:
1) The failure status code is 401, the passing status code is 200 (obviously)
2) When failing on travis, an extra response header is included: `Www-Authenticate: hawk`
3) When failing on travis, the response has `Content-Length: 447` but *no* content (`null`) whereas the passing version has `Content-Length: 74` and includes a response body.

It isn't clear to me why the content length would be 447, but there is an empty http response body. This indicates either a problem with the auth service, or a bug in the output of the test (suggesting a bug in the [google http library method called](https://developers.google.com/api-client-library/java/google-http-java-client/reference/1.20.0/com/google/api/client/http/HttpResponseException#getContent())).

Papertrail [logs](https://papertrailapp.com/systems/taskcluster-auth/events?selected=879863281785933841&focus=879863281785933841) do not shed a lot of insight:

```
Dec 19 20:49:35 taskcluster-auth heroku/router: at=info method=POST path="/v1/test-authenticate" host=auth.taskcluster.net request_id=8df949cb-b4f9-4c73-ba92-5311a1f63a51 fwd="52.45.185.117" dyno=web.5 connect=0ms service=2ms status=401 bytes=1180 protocol=https 
```

**Comment by petemoore** [comment]
Base 64 decoding the `ext` property included in the `Authorization` header in both cases gives as follows:

# Success (locally)
```
{"certificate":{"version":1,"scopes":["scope:1","scope:2"],"start":1513758863348,"expiry":1513762463348,"seed":"3VygcT_YSj29g63V9ssXOAuhcjT2KHQaeNbC2GET0vng","signature":"agJI3HcQorZHilQn0/ZJ4DN/Jai2dnnP952UeB2aGvg\u003d"}}

start (1513758863348): Mi 20 Dez 2017 09:34:23 CET
expiry (1513762463348): Mi 20 Dez 2017 10:34:23 CET
```

# Failure (travis)
```
{"certificate":{"version":1,"scopes":["scope:1","scope:2"],"start":1513712527717,"expiry":1513716127717,"seed":"z5oeR-mUTSiqRkJLqSWZDwuW7FoQdYRjOBoSRqJ6z1Wg","signature":"39sXuqz2Mzy3WNLDC71d7JEJ2WWBQbmipjwpYwSZpfQ\u003d"}}

start (1513712527717): Di 19 Dez 2017 20:42:07 CET
expiry (1513716127717): Di 19 Dez 2017 21:42:07 CET
```

**Comment by petemoore** [comment]
@jonasfj Any ideas?

**Comment by petemoore** [comment]
I've pushed an extra commit, let's see if this was an intermittent issue or not.

**Comment by petemoore** [comment]
So from pushing this extra commit, we see the "push" job failed, but the "pr" job passed. Previously, both failed.

Also, the response from the server is HTTP 401 suggesting that there was no `Authorization` header, yet from the logs, we see there was. If the auth was bad, we would expect to see an HTTP 403 not a 401 - so this also suggests a problem in the auth service.

**Comment by petemoore** [comment]
Let's review the failure case again:

The certificate data was:
```
{
  "certificate": {
    "version": 1,
    "scopes": [
      "scope:1",
      "scope:2"
    ],
    "start": 1513712527717,
    "expiry": 1513716127717,
    "seed": "z5oeR-mUTSiqRkJLqSWZDwuW7FoQdYRjOBoSRqJ6z1Wg",
    "signature": "39sXuqz2Mzy3WNLDC71d7JEJ2WWBQbmipjwpYwSZpfQ="
  }
}
```

We established already the start and expiry translate to:
```
start (1513712527717): Di 19 Dez 2017 20:42:07 CET
expiry (1513716127717): Di 19 Dez 2017 21:42:07 CET
```

We see from the travis log that the failure occurred at: `Dec 19, 2017 7:42:07 PM` in UTC time, which matches with the start time. However, if the travis worker clock was wrong, we would expect this. Let's compare to the server clock. The papertrail log that relates to this failure is:

```
Dec 19 20:42:06 taskcluster-auth heroku/router: at=info method=POST path="/v1/test-authenticate" host=auth.taskcluster.net request_id=b1caa6a7-9aec-44b5-bb89-686b502e727d fwd="52.45.185.117" dyno=web.1 connect=0ms service=3ms status=401 bytes=1177 protocol=https
```

The timestamp from papertrail is in my local timezone, which is CET - so here it looks like the server clock *might* be around one second behind the client clock - depending on how long it took to transmit the http response, and whether the log entry occurred before or after the http response was sent, etc.

I'm curious if the auth service allows requests from a temporary credential to have a start timestamp one second in the future or not. Note, the `start` and `expiry` fields are particular to our implementation (not general to hawk) so I presume our auth service directly validates these fields. I will test locally what happens if I push the start time one or two seconds into the future, to see if I can reproduce the 401 error locally.

**Comment by djmitche** [comment]
I was going to say "this seems like too much time to spend on an unused client", but I see you've found an actual bug, so carry on :)

**Pull request merged**
